trigger: none
pr:
  branches:
    include:
    - master
    - v*.*.x
  paths:
    exclude:
    - .git
    - .gitignore
    - /**/*.md
    - NEWS
    - AUTHORS

resources:
  containers:
    - container: centos7
      image: rdmz-harbor.rdmz.labs.mlnx/xpmem/x86_64/centos7
    - container: centos8
      image: rdmz-harbor.rdmz.labs.mlnx/xpmem/x86_64/centos8
    - container: ubuntu18
      image: rdmz-harbor.rdmz.labs.mlnx/xpmem/x86_64/ubuntu18.04
    - container: ubuntu20
      image: rdmz-harbor.rdmz.labs.mlnx/xpmem/x86_64/ubuntu20.04
    - container: ubuntu22
      image: rdmz-harbor.rdmz.labs.mlnx/xpmem/x86_64/ubuntu22.04


stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          name: MLNX
          demands:
            - harbor_registry

        strategy:
          matrix:
            centos7:
              build_container: centos7
            centos8:
              build_container: centos8
            ubuntu18:
              build_container: ubuntu18
            ubuntu20:
              build_container: ubuntu20
            ubuntu22:
              build_container: ubuntu22
        container: $[ variables['build_container'] ]

        steps:
          - checkout: self
            clean: true
            fetchDepth: 100
    
          - bash: |
              set -eEx
              ./autogen.sh
              kernel_ver=$(rpm -qa | grep kernel-devel | cut -d'-' -f3-)
              ./configure --with-kerneldir=/usr/src/kernels/${kernel_ver}
              make
            displayName: Build-$[ variables['build_container'] ]
            condition: contains(variables['build_container'], 'centos')

          - bash: |
              set -eEx
              ./autogen.sh
              kernel_ver=$(dpkg -l | grep 'linux-headers-.*-generic' | awk '{print $2}')
              ./configure --with-kerneldir=/usr/src/${kernel_ver}
              make
            displayName: Build-$[ variables['build_container'] ]
            condition: contains(variables['build_container'], 'ubuntu')
